import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {

    in property<string> result: "";
    in-out property<string> path: "";

    callback decompress(string);
    callback compress(string);
    callback browse_file();
    callback browse_folder();

    background: @linear-gradient(90deg, #2c3e50 0%,  #3498db 100%);
    GridLayout {
        padding: 50px;
        spacing: 20px;
        Row {            
            Text {
                text: "Decrypt";
                horizontal-alignment: center;
                font-size: 30px;
                font-weight: 1100;
            }
        }    

        Row {            
            GridLayout {                                
                spacing: 5px;                 
        
                folderpath := LineEdit {
                    font-size: 20px;
                    horizontal-alignment: center;
                    placeholder-text: "Enter the location";
                    height: 35px;
                    text <=> root.path;
                }
                Button {
                    text: "Browse";
                    height: 35px;                                        
                    clicked => { browse_folder(); }
                }
            }
        }

        Row {
            Button {
                text: "Compress";
                primary: true;
                height: 35px;
                clicked => {compress(folderpath.text)}                               
            }
        }

        Row {
            GridLayout {                
                spacing: 5px;                
        
                filepath := LineEdit {
                    font-size: 20px;
                    horizontal-alignment: center;
                    placeholder-text: "Enter the location";
                    height: 35px;
                    text <=> root.path;
                }
                Button {
                    text: "Browse";
                    height: 35px;                                        
                    clicked => { browse_file(); }
                }
            }
        }

        Row {
            Button {
                text: "Extract";
                primary: true;
                height: 35px;
                clicked => {decompress(filepath.text)}                               
            }
        }

        Row{
            VerticalBox {
                Rectangle {
                    background: #ffffff30;
                    height: 100px;
                    border-color: #ffffff34;
                    border-radius: 5px;
                    border-width: 0.7px;

                    Text{
                        color: #dfdfdf;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.result;
                    }
                }
            }
        }
    }
}
